spring:
  application:
    name: GestorIaTickets
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver

server:
  servlet:
    context-path: /gestoria/tickets/api

langchain4j:
  google-ai-gemini:
    chat-model:
      model-name: gemini-3.1-flash-lite
      timeout: 15s